server:
  port: 9091
spring:
  application:
    name: retailG-confirm-service
  datasource:
    url: jdbc:mysql://localhost:3306/confirmDB?createDatabaseIfNotExist=true
    username: root 
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9000/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin